### ISSUE TITLE
Registered customers

### ISSUE THREAD

**Issue by JoseManuelPedraja** [alex2276564/TelegramNotifier#3]
I'll try to add and try to make another message that is for registered customers...

When I have it I will add it here.

**Comment by alex2276564** [comment]
Hi @JoseManuelPedraja ,

Thank you for your suggestion! To clarify, are you requesting that the plugin send a notification to Telegram whenever a new customer registers on the PrestaShop store?

Please let me know if this is correct, and I will consider adding this feature.

**Comment by alex2276564** [comment]
@JoseManuelPedraja 

I'm pleased to inform you that the feature to send notifications for new customer registrations has been added in the latest version of TelegramNotifier, v1.0.5. You can download and install the new version from the [latest release page](https://github.com/alex2276564/TelegramNotifier/releases/latest).

This feature is disabled by default, so you can enable it in the settings if you wish to receive these notifications.

**Comment by alex2276564** [comment]
I am able to configure the module without any issues. Could you please provide more details about the problem you're experiencing? For example:

Are you unable to access the module's configuration page?
Are any settings not being saved after you click "Save"?
Have you tried reinstalling the module?

Additionally, I noticed that in release, I accidentally included the .git folder and some development files. This could potentially cause problems. I have now removed these files. Please try downloading the latest file from the latest release: https://github.com/alex2276564/TelegramNotifier/releases/latest.

**Comment by alex2276564** [comment]
Try this out:

Go into your server (for example, using FTP or SFTP), navigate to your PrestaShop directory, then go to the /modules folder. Find the folder named "TelegramNotifier" and delete it entirely.

After that, try reinstalling the module again.

**Comment by alex2276564** [comment]
Please try installing older versions of the TelegramNotifier module available [here](https://github.com/alex2276564/TelegramNotifier/releases) and check if the issue persists in those versions. If the problem does occur, then it likely isn't related to the module itself.

If the issue still exists, follow these steps:
1. Access your Docker container or Docker volume where PrestaShop is installed.
2. Navigate to the /modules directory.
3. Locate the TelegramNotifier folder and delete it from there, rather than doing it through the PrestaShop back office.
4. After that, go to "Advanced Parameters" in the PrestaShop admin panel, then to "Performance," and clear the cache.
